### ISSUE TITLE
Error when going to the Availability link on the DO page

### ISSUE THREAD

**Issue by code-jockey** [BAMRU-Tech/bamru_net#91] opened 2018-10-17 05:04 UTC
Go to the DO page:

https://staging.bamru.info/do/

Then click on the Availability link, which goes to this page:

https://staging.bamru.info/do/avail/?year=2018&quarter=3

You will get the following error:

Request Method: | GET
-- | --
http://staging.bamru.info/do/avail/?year=2018&quarter=3
2.0.5
AttributeError
Generic detail view DoMemberListView must be called with either an object pk or a slug.
/home/bamru/venv/lib/python3.5/site-packages/django/views/generic/detail.py in get_object, line 47
/home/bamru/venv/bin/python3
3.5.2
['/home/bamru/venv/bin',  '/home/bamru/repo',  '/home/bamru/venv/lib/python35.zip',  '/home/bamru/venv/lib/python3.5',  '/home/bamru/venv/lib/python3.5/plat-x86_64-linux-gnu',  '/home/bamru/venv/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/bamru/venv/lib/python3.5/site-packages',  '/home/bamru/repo']
Tue, 16 Oct 2018 21:59:26 -0700

**Comment by kduncklee** [comment] 2018-10-18 04:14
This is a duplicate of #85 item 3 and is fixed by #89.

**Closed by kduncklee** 2018-10-18 04:14 UTC

**Comment by kduncklee** [comment] 2018-10-18 04:16
Duplicate of #85 item 3.

Fixed by #89
