### ISSUE TITLE
Fix bug on DO shift sign up page

### ISSUE THREAD

**Issue by cody-barkley** [BAMRU-Tech/bamru_net#453] opened 2019-10-09 02:31 UTC
When you visit the quarterly DO signup page,  it marks all your weeks as unavailable.  Even if you don’t save it or mark any weeks, it marks all your weeks as unavailable.  This makes us think a bunch of people are singing up with zero availability, but they could be just visiting the page. 

I think you should have to save your availability for it to go into the database.  

Another alternative is that it starts out blank. So there are 3 states - blank, available, unavailable.

**Comment by kduncklee** [comment] 2019-11-15 03:35
The issue is that it creates the week entries when the page is loaded. This is needed to support the behavior that things are saved as soon as you edit them (like click a checkbox).

I see two options that maintain this behavior:
1) initial load has an empty list with a button to populate
2) (your second) default state is null and shows up as an indeterminate checkbox (https://css-tricks.com/indeterminate-checkboxes/). Users could then select available or not for each. My suggestion would be not to rotate back to indeterminate. It would go indeterminate->yes->no->yes->no->...

**Comment by cody-barkley** [comment] 2019-11-15 15:37
To my untrained eye, #1 looks simpler.  Do you agree?

Thanks,
Cody

**Comment by ctaylor451** [comment] 2019-11-16 04:24
Cody, are you saying it looks simpler for the user to understand or for us to implement?

**Comment by cody-barkley** [comment] 2019-11-16 14:17
I think it would be simpler for the user but I don’t fully understand option #2.  So please let me know if you think otherwise.

Thanks,
Cody

**Comment by ctaylor451** [comment] 2019-11-17 04:31
Back to you Kevin.  Tested it with false (regular compare is null)  seems
to work correctly.  Didn't change the DB scheme.

Once you change the value it toggles between true and false (never again
indeterminate)

**Comment by kduncklee** [comment] 2019-11-22 04:39
The indeterminate version is now implemented and working. I deleted all future entries from people looking ahead.

On the plan page, - indicates indeterminate and blank is unavailable. 'A' remains available.

**Comment by cody-barkley** [comment] 2019-11-22 15:12
Thanks, Kevin.  I can’t enter a comment unless I go into “edit” each week. I tried in Safari and Firefox.  Is that by design?

Thanks,
Cody

**Comment by kduncklee** [comment] 2019-11-23 04:12
Yes, there's currently no way to edit the comment inline.

**Comment by ctaylor451** [comment] 2019-11-27 06:22
Follow up:  @kduncklee  added some commentary (pro: explains how to use the page, con: doesn't fit on a single screen for me).

@ctaylor451 added simple inline editing for comments (pro: fast comment entry, con: doesn't work very well on mobile and @kduncklee commentary is slightly confusing).

@cody-barkley would you review on staging and let us know if we should keep the new changes or make additional changes

**Comment by cody-barkley** [comment] 2019-12-02 15:13
+Melina

Staging looks good.  Only bug I spotted was that it gave me the mobile website on Safari Desktop.  Worked fine on Firefox.

Thanks,
Cody

**Comment by cody-barkley** [comment] 2019-12-03 21:17
Hi Kevin and Craig,

Do you have an ETA as to when this update would go live?  We want to send out a request to the team to get people to enter their Q1 DO availability.

Thanks,
Cody

**Comment by ctaylor451** [comment] 2019-12-03 21:19
I'll push it to production

**Comment by ctaylor451** [comment] 2019-12-03 21:30
Everything should be live - upgraded host and client, pushed latest changes

I don't understand your comment about safari desktop mobile website.  We
only have one website, if you want me to look in to please let me know.

**Comment by cody-barkley** [comment] 2019-12-04 14:59
It’s just in staging and just in Safari, so I’m not concerned about it.  

Just FYI - screenshot below.  bamru.net <http://bamru.net/> on left, staging on right.


Thanks,
Cody

**Comment by kduncklee** [comment] 2019-12-15 02:13
Wording is fixed on staging.

The issue @cody-barkley was talking about was the reactive view on a narrow browser window.

Closing.

**Closed by kduncklee** 2019-12-15 02:13 UTC
Labels: P2, backend, frontend UI
